#!/usr/bin/ruby

require 'thor'
require 'rumy-main.rb'

class RumyCLI < Thor
  default_command :build

  desc "rumy build", "Execute Build"
  method_option "file", type: :string
  def build()
    rumyfile = 'build.rb'
    if options.key?("file") then
      rumyfile = options["file"]
    end
    load rumyfile
    exec_target :all
  end

  desc "rumy test", "Execute Tests"
  def test()
    load 'tests.rb'
    run_tests
  end

  desc "rumy clean", "Execute Clean"
  def clean()
    load 'build.rb'
    clean_target :all
  end

  desc "rumy deps_draw", "Draw dependence Graph"
  def deps_draw()
    load 'build.rb'
    draw_target :all
  end

  # Project Initializer for C++ Project
  desc "rumy cpp_init proj_name", "Generate C++ Project Template"
  def cpp_init(proj_name)
    cpp_init_project (proj_name)
  end

  # Project Initializer for Rust Project
  desc "rumy rust_init proj_name", "Generate Rust Project Template"
  def rust_init(proj_name)
    rust_init_project (proj_name)
  end

end

RumyCLI.start(ARGV)
