#!/usr/bin/ruby

require 'thor'
require 'rumy-main.rb'

class RumyCLI < Thor
  default_command :build

  desc "build", "Execute Build"
  method_option "file", type: :string
  def build()
    rumyfile = 'build.rb'
    if options.key?("file") then
      rumyfile = options["file"]
    end
    load rumyfile
    exec_target :all
  end

  desc "test", "Execute Tests"
  def test()
    load 'tests.rb'
    run_tests
  end

  desc "clean", "Execute Clean"
  def clean()
    load 'build.rb'
    clean_target :all
  end

  desc "deps_draw", "Draw dependence Graph"
  def deps_draw()
    load 'build.rb'
    draw_target :all
  end

  # Project Initializer for C++ Project
  desc "cpp_init proj_name", "Generate C++ Project Template"
  def cpp_init(proj_name)
    cpp_init_project (proj_name)
  end

  # Project Initializer for Rust Project
  desc "rust_init proj_name", "Generate Rust Project Template"
  def rust_init(proj_name)
    rust_init_project (proj_name)
  end

  # Project Initializer for Rust Project
  desc "clone-git repo_location", "Clone Git Repository"
  def clone_git(repo_location)
    rumy_clone_git(repo_location, repo_location.split('/').last.sub('.git', ''))
  end

  # Project Initializer for Rust Project
  desc "clone-git repo_location dir", "Clone Git Repository"
  def clone_git(repo_location, dir)
    rumy_clone_git(repo_location, dir)
  end

  desc "log-git repo_location", "Clone Git Repository"
  def log_git(file)
    rumy_log_git(file)
  end

end

RumyCLI.start(ARGV)
